config/routes.rb
Rails.application.routes.draw do

  get 'searches/search'
  get 'search/search'
  get 'homes/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :facilities do
    resources :reviews, only: ["new", "create", "update", "destroy"]
  end

  resources :users, only: [ "edit", "update"]
  root to: "homes#about"

  get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
  attachment :image

  has_many :reviews ,dependent: :destroy
  belongs_to :user

  validates :name,
    presence: true,
    uniqueness: true

  validates :address,
    presence: true,
    uniqueness: true

  validates :url,
    presence: true

  def self.looks(search, word)
    @facility = Facility.where("name LIKE?","%#{word}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :facility

  validates :body,presence: true
  validates :people,presence: true
  validates :usage_fee, presence: true
  validates :usage_time, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :facilities, dependent: :destroy

  validates :name,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    facilities_path
  end

end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :authenticate_user! ,except: [:show, :index ]


  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)
    @facility.user_id= current_user.id
    if @facility.save
      flash[:notice] = 'You have registered new facility successfully.'
      redirect_to new_facility_review_path(@facility.id)
    else
      render :new
    end

  end

  def index
    @facilities = Facility.page(params[:page]).reverse_order.per(5)
  end

  def show
    @facility = Facility.find(params[:id])
    @reviews = Review.where(facility_id: params[:id]).page(params[:page]).reverse_order.per(5)
    @reviews_all = Review.where(facility_id: params[:id])
  end

  def edit
    # 第二期作成
  end

  def update
    # 第二期作成
  end

  def destroy
    # 第二期作成
  end


  private
  def facility_params
    params.require(:facility).permit(:name, :body, :image, :address, :url)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user! ,except: [:show, :index ]

  def new
    @facility = Facility.find(params[:facility_id])
    @review = Review.new
  end

  def create
    facility = Facility.find(params[:facility_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.facility_id = facility.id
    if @review.save
      flash[:notice] = 'You have posted new review successfully.'
      redirect_to facility_path(params[:facility_id])
    else
      @facility = Facility.find(params[:facility_id])
      render :new
    end
  end

  def edit
    # 第二期作成
  end


  def update
    # 第二期作成
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    flash[:notice] = 'You have deleted successfully'
    redirect_to facility_path(params[:facility_id])
  end

  private
  def review_params
    params.require(:review).permit(:people, :borrowed_goods, :usage_fee, :body, :satisfaction, :usage_time)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @facilities = Facility.looks(params[:search], params[:word])
    p @facilities
  end


  private
  def search_params
    params.require(:search).permit(:word, :seach)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to edit_user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'You have updated your nickname successfully'
      redirect_to facilities_path
    else
      render :edit
    end

  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/locates_helper.rb
module LocatesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/facilities/_nologin.html.erb
<h2>Log in</h2>
<p>登録をすると、施設の新規登録やレビュー登録ができます</p>

<%= link_to "Log in", new_user_session_path ,class:"btn btn-primary" %>
<%= link_to "Sign up", new_user_registration_path ,class:"btn btn-success" %>

app/views/facilities/_sidebar.html.erb
<h2>User info</h2>
<table class='table'>
  <tr>
    <th>Name</th>
    <th><%= user.name %></th>
  </tr>
</table>
<div class='row'>
  <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
    ユーザー名変更
    <i class="fas fa-user-cog"></i>
  <% end %>

</div>

<hr>

<div>
  <h3>投稿履歴</h3>
  <% user.reviews.each do |r| %>
    <%= link_to facility_path(r.facility.id) do %>
      <%= r.created_at %><br>
      <%= r.facility.name %>
      <br>
    <% end %>
  <% end %>
</div>

app/views/facilities/index.html.erb
<main>
  <div class='container px-5 px-sm-0'>
    <p id="notice"><%= flash[:notice] %></p>

    <div class='row'>
      <div class='col-md-3 d-none d-md-block'>
        <% if user_signed_in? %>
          <%= render 'facilities/sidebar', user: current_user %>
        <% else %>
          <%= render 'facilities/nologin' %>
        <% end %>
      </div>

     <div class='col-md-8 offset-md-1'>
        <h2>Facility</h2>
        <p>お探しの施設がない場合、<%= link_to "こちらから登録" ,new_facility_path %>, </p>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th>Address</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @facilities.each do |f| %>
            <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag f, :image, :fill, 100, 100, format:'jpeg', fallback:"default-image.jpg" %>
                </td>
                <td>
                  <%= link_to facility_path(f.id) do %>
                    <%= f.name %>
                  <% end %>
                </td>
                <td><%= f.address %></td>
              </tr>
            </tbody>
          <% end %>
        </table>

        <%= paginate @facilities %>
      </div>
    </div>
  </div>
</main>

app/views/facilities/new.html.erb
<div class="container">
  <div class="row no-gutters ">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5 ">
      <h5 class="text-dark bg-light p-4 mb-0">New facility</h5>
      <div class="form-body p-4 ">
        <% if @facility.errors.any? %>
            <h2><%= @facility.errors.count %>error prohibited this obj from being saved:</h2>
            <ul>
            <% @facility.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>
        <%= form_with model: @facility, local:true do |f| %>
          <label for="Name">施設名</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :name, class:"form-control", placeholder:"施設名" %>
          </div>
          <label for="Name">住所</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-map-marked"></i></span>
            </div>
            <%= f.text_area :address, class:"form-control", rows:"3", placeholder:"例)杉並区泉3丁目〇×" %>
          </div>
          <label for="Name">施設のURL</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fab fa-internet-explorer"></i></span>
            </div>
            <%= f.url_field :url, class:"form-control", rows:"3", placeholder:"https://~" %>
          </div>
          <label for="Name">写真(任意)</label>
          <div class="input-group mb-3">
            <%= f.attachment_field :image, class: "w-100" %>
          </div>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/facilities/show.html.erb
<main>

  <div class="container px-5 px-sm-0">
    <p id="notice"><%= flash[:notice] %></p>
    <div class="row">
      <div class="col-md-3 d-none d-md-block">
        <% if user_signed_in? %>
          <%= render 'facilities/sidebar', user: current_user %>
        <% else %>
          <%= render 'facilities/nologin' %>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1" >
        <h2><%= @facility.name %></h2>
        <div class= "card">
          <div class="card-header">
            <%= attachment_image_tag @facility, :image, :fill, 400, 100, format:'jpeg', fallback:"default-image.jpg" , class:"card-image-top"%>
          </div>
          <div class="card-body">
              <%= @facility.address %><br>
              <%= link_to "サイトはこちら", @facility.url %><br>
            </ul>
            <p>updated by <%= @facility.user.name %></p>
          </div>
        </div>
        <hr>

        <h3><%= @reviews_all.count %>件のレビュー</h3>
          <p class="small">※正確な情報は各施設に確認してください</p>
          <%= link_to "レビュー追加", new_facility_review_path(@facility.id), class:"col-2 btn btn-sm btn-primary mb-2" %>

        <% @reviews.each do |r| %>
          <div class= "card w-100 mt-2">
            <div class="card-body">
              <h5 class="card-title"><%= r.updated_at.in_time_zone('Tokyo') %><br>posted by <strong><%= r.user.name %></strong></h5>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">満足度：<%= r.satisfaction %></li>
                <li class="list-group-item">利用人数：<%= r.people %></li>
                <li class="list-group-item">利用時間：<%= r.usage_time %></li>
                <li class="list-group-item">利用料：<%= r.usage_fee %>円</li>
                <li class="list-group-item">借用品：<%= r.borrowed_goods %></li>
                <li class="list-group-item">利用してみての感想：<%= r.body %></li>
                <% if current_user == r.user %>
                  <%= link_to "削除" ,facility_review_path(r.facility_id ,r.id), method: :delete,data: { confirm: "本当に削除しますか" }, class:"col-2  btn btn-danger btn-sm" %>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <%= paginate @reviews%>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main class="p-5 img1 content">
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container p-5'>
    <div class="row">
      <h1 class="px-3 mx-auto text-white text-center">Welcome to
        <strong>Sound Output</strong>!
      </h1>
    </div>
    <div class="row">
      <i class="fas fa-music fa-5x mx-auto mt-5 icon-color "></i></i>
    </div>
    <div class="row">
      <p class="mx-auto mt-5 text-white bg-dark p-2 rounded text-center">Sound Outputは、音出し場所に悩む学生・社会人の手助けをします。<br>
      フィードバックは<%= link_to "こちら", 'https://forms.gle/T291FdNF3LLQDhkF6' %></p>
    </div>

    <%= link_to facilities_path ,class:"btn btn-primary btn-lg btn-block" do %>
      Let's go
    <% end %>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer class="bg-dark  text-center p-3">
  <div class="container">
    <div class="row">
      <div class="mx-auto text-white ">
        <p>(c)2023 Senya Sano <br>
          フィードバックは<%= link_to "こちら", 'https://forms.gle/T291FdNF3LLQDhkF6' %></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      <a class="navbar-brand" href="/">
        <i class="fas fa-music"></i>
        <span>Sound Output</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <div class="search_form">
              <%= form_with url: search_path, local: true, method: :get ,class:"nav-link text-light" do |f| %>
                <%= f.text_field :word ,placeholder:"施設のキーワード"%>
                <%= f.submit "検索", class: "btn btn-primary btn-sm" %>
              <% end %>
            </div>
          </li>



          <% if user_signed_in? %>
          <li>
            <a class="nav-link text-light" href="/facilities" >
              <i class="fas fa-search"></i>一覧
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/facilities/new">
              <i class="fas fa-plus"></i>施設新規登録
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out" >
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/facilities">
              <i class="fas fa-home"></i>一覧
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search_form">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sound Output</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
      <div class="content">
      <%= render 'layouts/header' %>
      <!--各テンプレートを読み出す-->
      <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reviews/new.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0">

    <div class="row">
      <div class="col-md-3 d-none d-md-block">
        <% if user_signed_in? %>
          <%= render 'facilities/sidebar', user: current_user %>
        <% else %>
          <%= render 'facilities/nologin' %>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1" >
        <h2>New Review</h2>
        <div class= "card p-4">
          <h5 class="card-title"><%= @facility.name %></h5>
          <p>
            <%= @facility.address %><br>
            updated by <%= @facility.user.name %>
          </p>
        </div>
        <div class="shadow-lg rounded px-0 my-5">
        <div class="form-body p-4">
           <% if @review.errors.any? %>
            <h2><%= @review.errors.count %>error prohibited this obj from being saved:</h2>
            <ul>
            <% @review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>
          <%= form_with model: @review, url: facility_reviews_path, local:true do |f| %>
            <%= f.label :satisfaction ,"満足度(5段階)"%>
            <div>
              <%= f.select :satisfaction, [ [5],[4],[3],[2],[1] ], class:"form-control" %>
            </div>
            <label for="People">利用人数</label>
            <div class="input-group mb-3 ">
              <%= f.select :people, [ [1],[2],[3],[4],[5],[6],[7],[8],[9],['10人以上']], class:"form-control" %>
            </div>
            <label for="borrowed_goods">借用品・備品</label>
            <div class="input-group mb-3 ">
              <%= f.text_field :borrowed_goods, class:"form-control", rows:"3", placeholder:"(例)無料で譜面台を借りれます" %>
            </div>
            <label for="borrowed_goods">使用時間</label>
            <div class="input-group mb-3 ">
              <%= f.text_field :usage_time, class:"form-control", rows:"3", placeholder:"(例)3時間" %>
            </div>
            <label for="usage_fee">利用料</label>
            <div class="input-group mb-3 ">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true">円は除いた数</span>
              </div>
              <%= f.text_field :usage_fee, class:"form-control", rows:"3", placeholder:"(例)300" %>
            </div>
            <label for="body">感想</label>
            <div class="input-group mb-3 ">
              <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"例)部屋はきれいだった。受付の方の対応が良かった。" %>
            </div>
            <br>
            <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/searches/search.html.erb
<main>
  <div class='container px-5 px-sm-0'>
    <p id="notice"><%= flash[:notice] %></p>

    <div class='row'>
      <div class='col-md-3 d-none d-md-block'>
        <% if user_signed_in? %>
          <%= render 'facilities/sidebar', user: current_user %>
        <% else %>
          <%= render 'facilities/nologin' %>
        <% end %>
      </div>

     <div class='col-md-8 offset-md-1'>
        <h2>Facility</h2>
        <p>お探しの施設がない場合、<%= link_to "こちらから登録" ,new_facility_path %>, </p>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th>Address</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @facilities.each do |f| %>
            <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag f, :image, :fill, 100, 100, format:'jpeg', fallback:"default-image.jpg" %>
                </td>
                <td>
                  <%= link_to facility_path(f.id) do %>
                    <%= f.name %>
                  <% end %>
                </td>
                <td><%= f.address %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<!--第2期作成-->

<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">ユーザーネーム変更</h5>
      <div class="form-body p-4">
        <% if @user.errors.any? %>
          <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user, local:true do |f| %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, class:"form-control", placeholder:"名前" %>
          </div>
          <br>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>